server:
  port: 8763
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: jkstack-dsm
  zipkin:
    base-url: http://127.0.0.1:9411/
  boot:
    admin:
      client:
        url: http://127.0.0.1:8094/
  main:
    allow-bean-definition-overriding: true

# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: true
  okhttp:
    enabled: false