server:
  port: 8762
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        namespace: jkstack-dsm
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      client:
        url: http://127.0.0.1:8094

