server:
  port: 8094

spring:
  application:
    name: dsm-admin
  main:
    allow-bean-definition-overriding: true

# actable的配置信息
actable:
  table:
    auto: add
  model:
    pack: com.jkstack.dsm.admin.entity
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
