server:
  port: 8094

spring:
  application:
    name: dsm-admin
  security:
    user:
      name: root
      password: 123qweASD
  cloud:
    nacos:
      discovery:
        namespace: jkstack-dsm
        server-addr: 192.168.3.23:8848