server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true

#  本系统提供四种模式：
#  2.1 当actable.table.auto=create时，系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
#  2.2 当actable.table.auto=update时，系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
#  2.3 当actable.table.auto=none时，系统不做任何处理。
#  2.4 当actable.table.auto=add，新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
#  2.5 actable.model.pack这个配置是用来配置要扫描的用于创建表的对象的包名
#  2.6 actable.database.type这个是用来区别数据库的，预计会支持这四种数据库mysql/oracle/sqlserver/postgresql，但目前仅支持mysql
actable:
  table:
    auto: update
  model:
    pack: com.jkstack.dsm.user.entity
  database:
    type: mysql
mybatis:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

