server:
  port: 8088

spring:
  application:
    name: dsm-user
  main:
    allow-bean-definition-overriding: true

swagger:
  enable: true
  title: JKStack-DSM「用户管理」接口文档
  description: JKStack-DSM「用户管理」接口文档

    # actable的配置信息
actable:
  table:
    auto: add
  model:
    pack: com.jkstack.dsm.user.entity
  database:
    type: mysql

